var chapterinfo = [
  ["Harry Potter and the Sorcerer's Stone", 1, 1, 1, "The Boy Who Lived"],
  ["Harry Potter and the Sorcerer's Stone", 1, 2, 2, "The Vanishing Glass"],
  ["Harry Potter and the Sorcerer's Stone", 1, 3, 3, "The Letters from No One"],
  ["Harry Potter and the Sorcerer's Stone", 1, 4, 4, "The Keeper of Keys"],
  ["Harry Potter and the Sorcerer's Stone", 1, 5, 5, "Diagon Alley"],
  [
    "Harry Potter and the Sorcerer's Stone",
    1,
    6,
    6,
    "The Journey from Platform Nine and Three-Quarters",
  ],
  ["Harry Potter and the Sorcerer's Stone", 1, 7, 7, "The Sorting Hat"],
  ["Harry Potter and the Sorcerer's Stone", 1, 8, 8, "The Potions Master"],
  ["Harry Potter and the Sorcerer's Stone", 1, 9, 9, "The Midnight Duel"],
  ["Harry Potter and the Sorcerer's Stone", 1, 10, 10, "Hallowe'en"],
  ["Harry Potter and the Sorcerer's Stone", 1, 11, 11, "Quidditch"],
  ["Harry Potter and the Sorcerer's Stone", 1, 12, 12, "The Mirror of Erised"],
  ["Harry Potter and the Sorcerer's Stone", 1, 13, 13, "Nicholas Flamel"],
  [
    "Harry Potter and the Sorcerer's Stone",
    1,
    14,
    14,
    "Norbert the Norwegian Ridgeback",
  ],
  ["Harry Potter and the Sorcerer's Stone", 1, 15, 15, "The Forbidden Forest"],
  ["Harry Potter and the Sorcerer's Stone", 1, 16, 16, "Through the Trapdoor"],
  [
    "Harry Potter and the Sorcerer's Stone",
    1,
    17,
    17,
    "The Man with Two Faces",
  ],
  ["Harry Potter and the Chamber of Secrets", 2, 18, 1, "The Worst Birthday"],
  ["Harry Potter and the Chamber of Secrets", 2, 19, 2, "Dobby's Warning"],
  ["Harry Potter and the Chamber of Secrets", 2, 20, 3, "The Burrow"],
  [
    "Harry Potter and the Chamber of Secrets",
    2,
    21,
    4,
    "At Flourish and Blotts",
  ],
  ["Harry Potter and the Chamber of Secrets", 2, 22, 5, "The Whomping Willow"],
  ["Harry Potter and the Chamber of Secrets", 2, 23, 6, "Gilderoy Lockhart"],
  [
    "Harry Potter and the Chamber of Secrets",
    2,
    24,
    7,
    "Mudbloods and Murmurs",
  ],
  ["Harry Potter and the Chamber of Secrets", 2, 25, 8, "The Deathday Party"],
  [
    "Harry Potter and the Chamber of Secrets",
    2,
    26,
    9,
    "The Writing on the Wall",
  ],
  ["Harry Potter and the Chamber of Secrets", 2, 27, 10, "The Rogue Bludger"],
  ["Harry Potter and the Chamber of Secrets", 2, 28, 11, "The Duelling Club"],
  [
    "Harry Potter and the Chamber of Secrets",
    2,
    29,
    12,
    "The Polyjuice Potion",
  ],
  [
    "Harry Potter and the Chamber of Secrets",
    2,
    30,
    13,
    "The Very Secret Diary",
  ],
  ["Harry Potter and the Chamber of Secrets", 2, 31, 14, "Cornelius Fudge"],
  ["Harry Potter and the Chamber of Secrets", 2, 32, 15, "Aragog"],
  [
    "Harry Potter and the Chamber of Secrets",
    2,
    33,
    16,
    "The Chamber of Secrets",
  ],
  [
    "Harry Potter and the Chamber of Secrets",
    2,
    34,
    17,
    "The Heir of Slytherin",
  ],
  ["Harry Potter and the Chamber of Secrets", 2, 35, 18, "Dobby's Reward"],
  ["Harry Potter and the Prisoner of Azkaban", 3, 36, 1, "Owl Post"],
  [
    "Harry Potter and the Prisoner of Azkaban",
    3,
    37,
    2,
    "Aunt Marge's Big Mistake",
  ],
  ["Harry Potter and the Prisoner of Azkaban", 3, 38, 3, "The Knight Bus"],
  ["Harry Potter and the Prisoner of Azkaban", 3, 39, 4, "The Leaky Cauldron"],
  ["Harry Potter and the Prisoner of Azkaban", 3, 40, 5, "The Dementor"],
  [
    "Harry Potter and the Prisoner of Azkaban",
    3,
    41,
    6,
    "Talons and Tea Leaves",
  ],
  [
    "Harry Potter and the Prisoner of Azkaban",
    3,
    42,
    7,
    "The Boggart in the Wardrobe",
  ],
  [
    "Harry Potter and the Prisoner of Azkaban",
    3,
    43,
    8,
    "Flight of the Fat Lady",
  ],
  ["Harry Potter and the Prisoner of Azkaban", 3, 44, 9, "Grim Defeat"],
  ["Harry Potter and the Prisoner of Azkaban", 3, 45, 10, "The Marauder's Map"],
  ["Harry Potter and the Prisoner of Azkaban", 3, 46, 11, "The Firebolt"],
  ["Harry Potter and the Prisoner of Azkaban", 3, 47, 12, "The Patronus"],
  [
    "Harry Potter and the Prisoner of Azkaban",
    3,
    48,
    13,
    "Gryffindor versus Ravenclaw",
  ],
  ["Harry Potter and the Prisoner of Azkaban", 3, 49, 14, "Snape's Grudge"],
  [
    "Harry Potter and the Prisoner of Azkaban",
    3,
    50,
    15,
    "The Quidditch Final",
  ],
  [
    "Harry Potter and the Prisoner of Azkaban",
    3,
    51,
    16,
    "Professor Trelawney's Prediction",
  ],
  ["Harry Potter and the Prisoner of Azkaban", 3, 52, 17, "Cat, Rat, and Dog"],
  [
    "Harry Potter and the Prisoner of Azkaban",
    3,
    53,
    18,
    "Moony, Wormtail, Padfoot and Prongs",
  ],
  [
    "Harry Potter and the Prisoner of Azkaban",
    3,
    54,
    19,
    "The Servant of Lord Voldemort",
  ],
  [
    "Harry Potter and the Prisoner of Azkaban",
    3,
    55,
    20,
    "The Dementor's Kiss",
  ],
  ["Harry Potter and the Prisoner of Azkaban", 3, 56, 21, "Hermione's Secret"],
  ["Harry Potter and the Prisoner of Azkaban", 3, 57, 22, "Owl Post Again"],
  ["Harry Potter and the Goblet of Fire", 4, 58, 1, "The Riddle House"],
  ["Harry Potter and the Goblet of Fire", 4, 59, 2, "The Scar"],
  ["Harry Potter and the Goblet of Fire", 4, 60, 3, "The Invitation"],
  ["Harry Potter and the Goblet of Fire", 4, 61, 4, "Back to the Burrow"],
  ["Harry Potter and the Goblet of Fire", 4, 62, 5, "Weasley's Wizard Wheezes"],
  ["Harry Potter and the Goblet of Fire", 4, 63, 6, "The Portkey"],
  ["Harry Potter and the Goblet of Fire", 4, 64, 7, "Bagman and Crouch"],
  ["Harry Potter and the Goblet of Fire", 4, 65, 8, "The Quidditch World Cup"],
  ["Harry Potter and the Goblet of Fire", 4, 66, 9, "The Dark Mark"],
  ["Harry Potter and the Goblet of Fire", 4, 67, 10, "Mayhem at the Ministry"],
  [
    "Harry Potter and the Goblet of Fire",
    4,
    68,
    11,
    "Aboard the Hogwarts Express",
  ],
  [
    "Harry Potter and the Goblet of Fire",
    4,
    69,
    12,
    "The Triwizard Tournament",
  ],
  ["Harry Potter and the Goblet of Fire", 4, 70, 13, "Mad-Eye Moody"],
  ["Harry Potter and the Goblet of Fire", 4, 71, 14, "The Unforgivable Curses"],
  [
    "Harry Potter and the Goblet of Fire",
    4,
    72,
    15,
    "Beauxbatons and Durmstrang",
  ],
  ["Harry Potter and the Goblet of Fire", 4, 73, 16, "The Goblet of Fire"],
  ["Harry Potter and the Goblet of Fire", 4, 74, 17, "The Four Champions"],
  [
    "Harry Potter and the Goblet of Fire",
    4,
    75,
    18,
    "The Weighing of the Wands",
  ],
  ["Harry Potter and the Goblet of Fire", 4, 76, 19, "The Hungarian Horntail"],
  ["Harry Potter and the Goblet of Fire", 4, 77, 20, "The First Task"],
  [
    "Harry Potter and the Goblet of Fire",
    4,
    78,
    21,
    "The House-Elf Liberation Front",
  ],
  ["Harry Potter and the Goblet of Fire", 4, 79, 22, "The Unexpected Task"],
  ["Harry Potter and the Goblet of Fire", 4, 80, 23, "The Yule Ball"],
  ["Harry Potter and the Goblet of Fire", 4, 81, 24, "Rita Skeeter's Scoop"],
  ["Harry Potter and the Goblet of Fire", 4, 82, 25, "The Egg and the Eye"],
  ["Harry Potter and the Goblet of Fire", 4, 83, 26, "The Second Task"],
  ["Harry Potter and the Goblet of Fire", 4, 84, 27, "Padfoot Returns"],
  [
    "Harry Potter and the Goblet of Fire",
    4,
    85,
    28,
    "The Madness of Mr Crouch",
  ],
  ["Harry Potter and the Goblet of Fire", 4, 86, 29, "The Dream"],
  ["Harry Potter and the Goblet of Fire", 4, 87, 30, "The Pensieve"],
  ["Harry Potter and the Goblet of Fire", 4, 88, 31, "The Third Task"],
  ["Harry Potter and the Goblet of Fire", 4, 89, 32, "Flesh, Blood, and Bone"],
  ["Harry Potter and the Goblet of Fire", 4, 90, 33, "The Death Eaters"],
  ["Harry Potter and the Goblet of Fire", 4, 91, 34, "Priori Incantatem"],
  ["Harry Potter and the Goblet of Fire", 4, 92, 35, "Veritaserum"],
  ["Harry Potter and the Goblet of Fire", 4, 93, 36, "The Parting of the Ways"],
  ["Harry Potter and the Goblet of Fire", 4, 94, 37, "The Beginning"],
  ["Harry Potter and the Order of the Phoenix", 5, 95, 1, "Dudley Demented"],
  ["Harry Potter and the Order of the Phoenix", 5, 96, 2, "A Peck of Owls"],
  ["Harry Potter and the Order of the Phoenix", 5, 97, 3, "The Advance Guard"],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    98,
    4,
    "Number Twelve, Grimmauld Place",
  ],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    99,
    5,
    "The Order of the Phoenix",
  ],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    100,
    6,
    "The Noble and Most Ancient House of Black",
  ],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    101,
    7,
    "The Ministry of Magic",
  ],
  ["Harry Potter and the Order of the Phoenix", 5, 102, 8, "The Hearing"],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    103,
    9,
    "The Woes of Mrs Weasley",
  ],
  ["Harry Potter and the Order of the Phoenix", 5, 104, 10, "Luna Lovegood"],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    105,
    11,
    "The Sorting Hat's New Song",
  ],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    106,
    12,
    "Professor Umbridge",
  ],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    107,
    13,
    "Detention with Dolores",
  ],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    108,
    14,
    "Percy and Padfoot",
  ],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    109,
    15,
    "The Hogwarts High Inquisitor",
  ],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    110,
    16,
    "In the Hog's Head",
  ],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    111,
    17,
    "Educational Decree Number Twenty-four",
  ],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    112,
    18,
    "Dumbledore's Army",
  ],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    113,
    19,
    "The Lion and the Serpent",
  ],
  ["Harry Potter and the Order of the Phoenix", 5, 114, 20, "Hagrid's Tale"],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    115,
    21,
    "The Eye of the Snake",
  ],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    116,
    22,
    "St Mungo's Hospital for Magical Maladies and Injuries",
  ],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    117,
    23,
    "Christmas on the Closed Ward",
  ],
  ["Harry Potter and the Order of the Phoenix", 5, 118, 24, "Occlumency"],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    119,
    25,
    "The Beetle at Bay",
  ],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    120,
    26,
    "Seen and Unforeseen",
  ],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    121,
    27,
    "The Centaur and the Sneak",
  ],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    122,
    28,
    "Snape's Worst Memory",
  ],
  ["Harry Potter and the Order of the Phoenix", 5, 123, 29, "Career Advice"],
  ["Harry Potter and the Order of the Phoenix", 5, 124, 30, "Grawp"],
  ["Harry Potter and the Order of the Phoenix", 5, 125, 31, "O.W.L.S"],
  ["Harry Potter and the Order of the Phoenix", 5, 126, 32, "Out of the Fire"],
  ["Harry Potter and the Order of the Phoenix", 5, 127, 33, "Fight and Flight"],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    128,
    34,
    "The Department of Mysteries",
  ],
  ["Harry Potter and the Order of the Phoenix", 5, 129, 35, "Beyond the Veil"],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    130,
    36,
    "The Only One He Ever Feared",
  ],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    131,
    37,
    "The Lost Prophecy",
  ],
  [
    "Harry Potter and the Order of the Phoenix",
    5,
    132,
    38,
    "The Second War Begins",
  ],
  ["Harry Potter and the Half-Blood Prince", 6, 133, 1, "The Other Minister"],
  ["Harry Potter and the Half-Blood Prince", 6, 134, 2, "Spinner's End"],
  ["Harry Potter and the Half-Blood Prince", 6, 135, 3, "Will and Won't"],
  ["Harry Potter and the Half-Blood Prince", 6, 136, 4, "Horace Slughorn"],
  ["Harry Potter and the Half-Blood Prince", 6, 137, 5, "An Excess of Phlegm"],
  ["Harry Potter and the Half-Blood Prince", 6, 138, 6, "Draco's Detour"],
  ["Harry Potter and the Half-Blood Prince", 6, 139, 7, "The Slug Club"],
  ["Harry Potter and the Half-Blood Prince", 6, 140, 8, "Snape Victorious"],
  [
    "Harry Potter and the Half-Blood Prince",
    6,
    141,
    9,
    "The Half-Blood Prince",
  ],
  ["Harry Potter and the Half-Blood Prince", 6, 142, 10, "The House of Gaunt"],
  [
    "Harry Potter and the Half-Blood Prince",
    6,
    143,
    11,
    "Hermione's Helping Hand",
  ],
  ["Harry Potter and the Half-Blood Prince", 6, 144, 12, "Silver and Opals"],
  ["Harry Potter and the Half-Blood Prince", 6, 145, 13, "The Secret Riddle"],
  ["Harry Potter and the Half-Blood Prince", 6, 146, 14, "Felix Felicis"],
  ["Harry Potter and the Half-Blood Prince", 6, 147, 15, "The Unbreakable Vow"],
  [
    "Harry Potter and the Half-Blood Prince",
    6,
    148,
    16,
    "A Very Frosty Christmas",
  ],
  ["Harry Potter and the Half-Blood Prince", 6, 149, 17, "A Sluggish Memory"],
  ["Harry Potter and the Half-Blood Prince", 6, 150, 18, "Birthday Surprises"],
  ["Harry Potter and the Half-Blood Prince", 6, 151, 19, "Elf Tails"],
  [
    "Harry Potter and the Half-Blood Prince",
    6,
    152,
    20,
    "Lord Voldemort's Request",
  ],
  ["Harry Potter and the Half-Blood Prince", 6, 153, 21, "The Unknowable Room"],
  ["Harry Potter and the Half-Blood Prince", 6, 154, 22, "After the Burial"],
  ["Harry Potter and the Half-Blood Prince", 6, 155, 23, "Horcruxes"],
  ["Harry Potter and the Half-Blood Prince", 6, 156, 24, "Sectumsempra"],
  ["Harry Potter and the Half-Blood Prince", 6, 157, 25, "The Seer Overheard"],
  ["Harry Potter and the Half-Blood Prince", 6, 158, 26, "The Cave"],
  [
    "Harry Potter and the Half-Blood Prince",
    6,
    159,
    27,
    "The Lightning Struck Tower",
  ],
  [
    "Harry Potter and the Half-Blood Prince",
    6,
    160,
    28,
    "Flight of the Prince",
  ],
  ["Harry Potter and the Half-Blood Prince", 6, 161, 29, "The Phoenix Lament"],
  ["Harry Potter and the Half-Blood Prince", 6, 162, 30, "The White Tomb"],
  [
    "Harry Potter and the Deathly Hallows",
    7,
    163,
    1,
    "The Dark Lord Ascending",
  ],
  ["Harry Potter and the Deathly Hallows", 7, 164, 2, "In Memoriam"],
  ["Harry Potter and the Deathly Hallows", 7, 165, 3, "The Dursleys Departing"],
  ["Harry Potter and the Deathly Hallows", 7, 166, 4, "The Seven Potters"],
  ["Harry Potter and the Deathly Hallows", 7, 167, 5, "Fallen Warrior"],
  ["Harry Potter and the Deathly Hallows", 7, 168, 6, "The Ghoul in Pyjamas"],
  [
    "Harry Potter and the Deathly Hallows",
    7,
    169,
    7,
    "The Will of Albus Dumbledore",
  ],
  ["Harry Potter and the Deathly Hallows", 7, 170, 8, "The Wedding"],
  ["Harry Potter and the Deathly Hallows", 7, 171, 9, "A Place to Hide"],
  ["Harry Potter and the Deathly Hallows", 7, 172, 10, "Kreacher's Tale"],
  ["Harry Potter and the Deathly Hallows", 7, 173, 11, "The Bribe"],
  ["Harry Potter and the Deathly Hallows", 7, 174, 12, "Magic is Might"],
  [
    "Harry Potter and the Deathly Hallows",
    7,
    175,
    13,
    "The Muggle-Born Registration Commission",
  ],
  ["Harry Potter and the Deathly Hallows", 7, 176, 14, "The Thief"],
  ["Harry Potter and the Deathly Hallows", 7, 177, 15, "The Goblin's Revenge"],
  ["Harry Potter and the Deathly Hallows", 7, 178, 16, "Godric's Hollow"],
  ["Harry Potter and the Deathly Hallows", 7, 179, 17, "Bathilda's Secret"],
  [
    "Harry Potter and the Deathly Hallows",
    7,
    180,
    18,
    "The Life and Lies of Albus Dumbledore",
  ],
  ["Harry Potter and the Deathly Hallows", 7, 181, 19, "The Silver Doe"],
  ["Harry Potter and the Deathly Hallows", 7, 182, 20, "Xenophilius Lovegood"],
  [
    "Harry Potter and the Deathly Hallows",
    7,
    183,
    21,
    "The Tale of the Three Brothers",
  ],
  ["Harry Potter and the Deathly Hallows", 7, 184, 22, "The Deathly Hallows"],
  ["Harry Potter and the Deathly Hallows", 7, 185, 23, "Malfoy Manor"],
  ["Harry Potter and the Deathly Hallows", 7, 186, 24, "The Wandmaker"],
  ["Harry Potter and the Deathly Hallows", 7, 187, 25, "Shell Cottage"],
  ["Harry Potter and the Deathly Hallows", 7, 188, 26, "Gringotts"],
  [
    "Harry Potter and the Deathly Hallows",
    7,
    189,
    27,
    "The Final Hiding Place",
  ],
  ["Harry Potter and the Deathly Hallows", 7, 190, 28, "The Missing Mirror"],
  ["Harry Potter and the Deathly Hallows", 7, 191, 29, "The Lost Diadem"],
  [
    "Harry Potter and the Deathly Hallows",
    7,
    192,
    30,
    "The Sacking of Severus Snape",
  ],
  [
    "Harry Potter and the Deathly Hallows",
    7,
    193,
    31,
    "The Battle of Hogwarts",
  ],
  ["Harry Potter and the Deathly Hallows", 7, 194, 32, "The Elder Wand"],
  ["Harry Potter and the Deathly Hallows", 7, 195, 33, "The Prince's Tale"],
  ["Harry Potter and the Deathly Hallows", 7, 196, 34, "The Forest Again"],
  ["Harry Potter and the Deathly Hallows", 7, 197, 35, "King's Cross"],
  ["Harry Potter and the Deathly Hallows", 7, 198, 36, "The Flaw in the Plan"],
  ["Harry Potter and the Deathly Hallows", 7, 199, 37, "Epilogue"],
];
